services:
  decktape:
    command: ["--size", "${PDF_VIEWPORT:-{{ cookiecutter.pdf_viewport }}}", "reveal", "http://slides?showNotes=true", "{{ cookiecutter.repo_name }}.pdf"]
    depends_on:
      - nginx
    image: astefanutti/decktape:2.8.3@sha256:1a941d17c54e79ce812019a7f89553c5ddbd4109425fe87e18a4506530c7cc3c
    volumes:
      - .:/slides
  nginx:
    image: nginx:1.21.0-alpine@sha256:6d76a25a64f6a9a873bded796761bf7a1d18367570281d73d16750ce37fae297
    networks:
      default:
        aliases:
          - slides
    volumes:
      - .:/usr/share/nginx/html:ro
version: '3'
